name: Okuna
description: Social Network

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.1+99

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dependencies:
  collection: ^1.15.0
  exif: ^3.1.4
  html: ^0.15.0
  expandable: ^5.0.1
  uuid: ^3.0.4
  flutter_image_compress: ^2.0.4
  inview_notifier_list:
    git:
      url: https://github.com/OkunaOrg/inview_notifier_list.git
      ref: e52a3bb077dfb8815e6b7ac51f98ae1603ff26b2
  connectivity: ^3.0.6
  visibility_detector: ^0.4.0+2
  http_retry: ^0.2.0
  video_thumbnail: ^0.5.3
  ffmpeg_kit_flutter: ^6.0.0
  open_iconic_flutter:
    git:
      url: https://github.com/pictofeed/open_iconic_flutter.git
      ref: 2d841baacd14bf5cd43b92f654f309cd7c5d1b97
  retry: ^3.1.0
  shared_preferences: ^2.0.8
  flutter_markdown: ^0.6.6
  file_picker: ^5.2.10
  sentry_flutter: ^7.9.0
  screen:
    git:
      url: https://github.com/pictofeed/flutter_screen.git
      ref: 7dd6c22962df75ef21d3371eb18991621aa901ee
  back_button_interceptor: ^7.0.0
  flutter_colorpicker: ^1.0.3
  intercom_flutter: ^7.8.4
  device_info: ^2.0.2
  flutter_pagewise: ^2.0.1
  tinycolor2: ^3.0.1
  onesignal_flutter:
    git:
      url: https://github.com/OneSignal/OneSignal-Flutter-SDK.git
      ref: d553e738cac741df98c5d99c5a485522e526edc0
  flutter_advanced_networkimage:
    git:
      url: https://github.com/jozsefsallai/flutter_advanced_networkimage.git
      ref: 0b2c9775f8ab375c47f812a459f276b9feb107b8
  dcache: ^0.4.0
  validators: ^3.0.0
  url_launcher: ^6.0.12
  uni_links: ^0.5.1
  flutter_slidable: ^3.0.0
  flutter_cache_manager: ^3.1.0
  cached_network_image: ^3.1.0
  timeago: ^3.1.0
  public_suffix: ^3.0.0
  pigment: ^1.0.4
  photo_view: ^0.14.0
  flutter_svg: ^0.22.0
  flutter_secure_storage: ^8.0.0
  mime: ^1.0.0
  http: ^0.13.3
  throttling: ^1.0.0
  wakelock: ^0.6.2
  rxdart: ^0.27.2
  video_player:
    git:
      url: https://github.com/pictofeed/flutter-packages.git
      path: packages/video_player/video_player
  sprintf: ^7.0.0
  image_picker: ^1.0.2
  image_cropper: ^4.0.1
  shimmer: ^3.0.0
  share_plus: ^6.3.4
  path: ^1.8.0
  package_info: ^2.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  intl_generator: ^0.4.1

# VERY HACKY WORKAROUND. This is temporary until `flutter_launcher_icons` and
# `intl_generator` are playing nice with each other.
dependency_overrides:
  args: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/images/icon-adaptive-foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/theme-previews/theme-preview-dark.png
    - assets/images/theme-previews/theme-preview-colorful.png
    - assets/images/theme-previews/theme-preview-dark-gold.png
    - assets/images/theme-previews/theme-preview-white.png
    - assets/images/theme-previews/theme-preview-white-gold.png
    - assets/images/theme-previews/theme-preview-space-blue.png
    - assets/images/theme-previews/theme-preview-light-blue.png
    - assets/images/theme-previews/theme-preview-light-rose.png
    - assets/images/theme-previews/theme-preview-space-rose.png
    - assets/images/theme-previews/theme-preview-light-cinnabar.png
    - assets/images/theme-previews/theme-preview-space-cinnabar.png
    - assets/images/theme-previews/theme-preview-light-royale.png
    - assets/images/theme-previews/theme-preview-space-royale.png
    - assets/images/splash-background.png
    - assets/images/openbook-o-logo.png
    - assets/images/pixel-universe.jpg
    - assets/images/confetti-background.gif
    - assets/images/icons/gif-icon.png
    - assets/images/icons/profile-icon.png
    - assets/images/icons/connections-icon.png
    - assets/images/icons/burner-icon.png
    - assets/images/icons/settings-icon.png
    - assets/images/icons/help-icon.png
    - assets/images/icons/thinking.gif
    - assets/images/icons/customize-icon.png
    - assets/images/icons/logout-icon.png
    - assets/images/icons/audience-icon.png
    - assets/images/icons/home-icon.png
    - assets/images/icons/notifications-icon.png
    - assets/images/icons/search-icon.png
    - assets/images/icons/communities-icon.png
    - assets/images/icons/create-post-icon.png
    - assets/images/icons/chat-icon.png
    - assets/images/icons/photo-icon.png
    - assets/images/icons/video-icon.png
    - assets/images/icons/camera-icon.png
    - assets/images/icons/warning-icon.png
    - assets/images/icons/success-icon.png
    - assets/images/icons/error-icon.png
    - assets/images/icons/info-icon.png
    - assets/images/icons/comments-icon.png
    - assets/images/icons/comment-icon.png
    - assets/images/icons/react-icon.png
    - assets/images/icons/like-icon.png
    - assets/images/icons/finish-icon.png
    - assets/images/icons/finish-icon.png
    - assets/images/icons/expand-icon.png
    - assets/images/icons/load-more-posts-icon.gif
    - assets/images/categories/category_all-min.png
    - assets/images/fallbacks/post-fallback.png
    - assets/images/fallbacks/cover-fallback.jpg
    - assets/images/fallbacks/avatar-fallback.jpg
    - assets/other/public_suffix_list.dat
    - .env.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          style: normal
        - asset: assets/fonts/NunitoSans-Bold.ttf
          style: italic
    - family: VisbyRoundCF
      fonts:
        - asset: assets/fonts/VisbyRoundCF-Regular.otf
          style: normal
        - asset: assets/fonts/VisbyRoundCF-Bold.otf
          style: italic
    - family: CogogooseProSemilight
      fonts:
        - asset: assets/fonts/Cocogoose-Pro-Semilight.ttf
          style: normal
    - family: ""
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
